basePath: /
consumes:
    - application/json
definitions:
    ErrResponse:
        description: Reference will be omitted if it does not exist.
        title: ErrResponse defines the return messages when an error occurred.
        x-go-package: github.com/marmotedu/component-base/pkg/core
host: some-url.com
info:
    description: Documentation of our awesome API.
    title: awesome.
    version: 0.1.0
paths: {}
produces:
    - application/json
schemes:
    - http
    - https
securityDefinitions:
    basic:
        type: basic
swagger: "2.0"
