apiVersion: v1
kind: Service
metadata:
  name: {{ include "cas-apiserver.fullname" . }}
  labels:
    {{- include "cas-apiserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.port }}
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "cas-apiserver.selectorLabels" . | nindent 4 }}
