name: CI

on:
  push:
    branchs:
      - '*'
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          skip-pkg-cache: true
          skip-build-cache: true
